"""phase 1 initial schema

Revision ID: 7587684d7941
Revises: 
Create Date: 2026-06-30 23:22:25.263671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7587684d7941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('otp_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('constituency_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('constituency_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('idx_issues_category', ['category'], unique=False)
        batch_op.create_index('idx_issues_constituency', ['constituency_id'], unique=False)
        batch_op.create_index('idx_issues_created', ['created_at'], unique=False)
        batch_op.create_index('idx_issues_status', ['status'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index('idx_sync_status', ['synced_at'], unique=False)
        batch_op.create_index('idx_sync_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index('idx_sync_user')
        batch_op.drop_index('idx_sync_status')

    op.drop_table('sync_log')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('idx_issues_status')
        batch_op.drop_index('idx_issues_created')
        batch_op.drop_index('idx_issues_constituency')
        batch_op.drop_index('idx_issues_category')

    op.drop_table('issues')
    op.drop_table('users')
    op.drop_table('otp_sessions')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
