"""add issues.client_id for idempotent sync

Revision ID: ab75a3bd7795
Revises: cdbe7cbbd3b8
Create Date: 2026-07-01 00:25:32.394804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab75a3bd7795'
down_revision: Union[str, None] = 'cdbe7cbbd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint('uq_issues_user_client', ['user_id', 'client_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint('uq_issues_user_client', type_='unique')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
