"""add otp_sessions.attempts

Revision ID: cdbe7cbbd3b8
Revises: 7587684d7941
Create Date: 2026-06-30 23:44:42.757576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbe7cbbd3b8'
down_revision: Union[str, None] = '7587684d7941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows; NOT NULL is then safe.
    with op.batch_alter_table('otp_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'attempts', sa.Integer(), nullable=False, server_default='0'
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_sessions', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
